# * 这另一个 GitHub Actions 的配置文件（YAML 格式），用于定义发布流程。该文件包括以下内容：

# * 定义了工作流的名称为 "Publish"。
# * 触发条件为推送标签以及对并发策略的设置。
# * 定义了一个名为 "dist" 的 job，该 job 在 ubuntu-latest 环境下运行。
# * 使用了一个矩阵策略，指定了操作系统和 Python 版本的组合。
# * 包含了一系列步骤，包括设置 Python 环境、安装依赖、构建分发包、以及上传分发包的步骤。


# * 这些步骤将在满足特定条件时执行，例如只有在 ubuntu-latest 环境下才执行构建分发包和上传分发包的步骤。

name: Publish

on:
  push:
    tags:
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dist:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Install dependencies
      run: make develop

    - name: Make dist
      run: make dist
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - uses: actions/upload-artifact@v4
      with:
        path: ./dist/*.tar.gz
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - uses: actions/upload-artifact@v4
      with:
        path: ./dist/*.whl
